MAX_HANDS = 1
DETECTION_CONFIDENCE = 0.75
TRACKING_CONFIDENCE = 0.75

THUMB_TOGGLE_COOLDOWN = 2
SCREENSHOT_COOLDOWN = 3

PINCH_THRESHOLD = 30
DEADZONE = 15

SCROLL_SMOOTHING = 0.85
SCROLL_MULTIPLIER = 0.6
FREEZE_DURATION = 1.5
